import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import { recruitmentChallengeAPI } from "@/api/recruitmentChallenge";
import { Container } from "react-bootstrap";
import Loading from "@/components/Loading";
import UsersTable from "@/components/UsersTable";
import Error from "@/components/Error";
import { limitData } from "@/utils/limitData";

export default function Home() {
  const [data, setData] = useState([]);
  const [error, setError] = useState(false);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1);

  useEffect(() => {
    recruitmentChallengeAPI()
      .then(setData)
      .catch(() => setError(true))
      .finally(() => setLoading(false));

    window.addEventListener("scroll", loadMore);
    return () => {
      window.removeEventListener("scroll", loadMore);
    };
  }, []);

  const limitedData = limitData(data, page);

  function loadMore() {
    if (limitData(data, page + 1).length === limitData(data, page).length)
      return;

    if (
      window.innerHeight + document.documentElement.scrollTop ===
      document.scrollingElement.scrollHeight
    ) {
      setPage((prevState) => prevState + 1);
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Container className="text-center my-3">
          {error ? (
            <Error />
          ) : loading ? (
            <Loading />
          ) : (
            <UsersTable data={limitedData} />
          )}
        </Container>
      </main>
    </>
  );
}
